import blockContent from './blockContent'
import SeparationCoachenBild from './image1'
import juridiskBild from './image2'
import pictureOfMe from './image3'
import JuridiskHjalp from './juridisk-hjalp'
import Ommig from './om-mig'
import separation from './separations-Coachen'
import Tappning from './tappning'
import paketEtt from './paketEtt'
import paketTva from './paketTva'
import paketTre from './paketTre'
import PaketFyra from './paketFyra'
import menyEtt from './navEtt'
import menyTva from './menyTva'
import menyTre from './menyTre'
import menyFyra from './menyFyra'
import menyFem from './menyFem'
import logoBild from './loggaimg'


export const schemaTypes = [logoBild,separation,SeparationCoachenBild, juridiskBild,JuridiskHjalp,Tappning,paketEtt, paketTva, paketTre, PaketFyra, Ommig, pictureOfMe,  blockContent,  menyEtt, menyTva, menyTre, menyFyra, menyFem]
